# Generated by Django 5.0.7 on 2024-07-18 22:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Costumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('identification_type', models.CharField(choices=[('DNI', 'DNI'), ('RUC', 'RUC'), ('CE', 'Carnet de Extranjería')], max_length=3, verbose_name='Tipo de identificación')),
                ('vat', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Número de identificación')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('is_occasional', models.BooleanField(default=False, verbose_name='Es ocasional')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Dirección')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo electrónico')),
                ('country', models.CharField(blank=True, max_length=50, null=True, verbose_name='País')),
                ('city', models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad')),
                ('ruc', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUC')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('stock_min', models.PositiveIntegerField(default=0, verbose_name='Stock mínimo')),
                ('stock_max', models.PositiveIntegerField(default=100, verbose_name='Stock máximo')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Imagen')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='ProductCostumer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('costumer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.costumer', verbose_name='Cliente')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Venta de Producto',
                'verbose_name_plural': 'Ventas de Productos',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('warehouse_location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ubicación en almacén')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('type', models.CharField(choices=[('In', 'Ingreso'), ('Out', 'Salida')], max_length=3, verbose_name='Tipo')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notas')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Movimiento de Stock',
                'verbose_name_plural': 'Movimientos de Stock',
            },
        ),
        migrations.CreateModel(
            name='ProductSupplier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('number_invoicing', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de factura')),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio de compra')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.supplier', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra de Producto',
                'verbose_name_plural': 'Compras de Productos',
            },
        ),
    ]
